import SwiftUI

/// Welcome/Login screen
struct WelcomeView: View {
    @StateObject private var viewModel = LoginViewModel(authManager: AuthManager.shared)

    var body: some View {
        NavigationStack {
            ZStack {
                ScrollView {
                    VStack(spacing: DesignSystem.Spacing.xxxl) {
                        // Header
                        VStack(spacing: DesignSystem.Spacing.md) {
                            Text("AIQ")
                                .font(Typography.displayMedium)
                                .foregroundColor(ColorPalette.primary)

                            Text("AI-Generated Cognitive Assessment")
                                .font(Typography.bodyLarge)
                                .foregroundColor(ColorPalette.textSecondary)
                                .multilineTextAlignment(.center)

                            Text(
                                """
                                Track your cognitive performance with fresh challenges \
                                generated by AI. Designed for personal insight and growth.
                                """
                            )
                            .font(Typography.bodySmall)
                            .foregroundColor(ColorPalette.textSecondary)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, DesignSystem.Spacing.md)
                        }
                        .padding(.top, DesignSystem.Spacing.section)

                        // Login Form
                        VStack(spacing: DesignSystem.Spacing.xl) {
                            CustomTextField(
                                title: "Email",
                                placeholder: "your.email@example.com",
                                text: $viewModel.email,
                                keyboardType: .emailAddress,
                                autocapitalization: .never
                            )

                            if let emailError = viewModel.emailError {
                                Text(emailError)
                                    .font(Typography.captionMedium)
                                    .foregroundColor(ColorPalette.error)
                                    .frame(maxWidth: .infinity, alignment: .leading)
                            }

                            CustomTextField(
                                title: "Password",
                                placeholder: "Enter your password",
                                text: $viewModel.password,
                                isSecure: true
                            )

                            if let passwordError = viewModel.passwordError {
                                Text(passwordError)
                                    .font(Typography.captionMedium)
                                    .foregroundColor(ColorPalette.error)
                                    .frame(maxWidth: .infinity, alignment: .leading)
                            }

                            PrimaryButton(
                                title: "Sign In",
                                action: {
                                    Task {
                                        await viewModel.login()
                                    }
                                },
                                isLoading: viewModel.isLoading,
                                isDisabled: !viewModel.isFormValid
                            )
                            .padding(.top, DesignSystem.Spacing.sm)
                        }

                        // Error Display
                        if let error = viewModel.error {
                            ErrorBanner(
                                message: error.localizedDescription,
                                onDismiss: {
                                    viewModel.clearError()
                                }
                            )
                        }

                        // Registration Link
                        VStack(spacing: DesignSystem.Spacing.md) {
                            Text("Don't have an account?")
                                .font(Typography.bodyMedium)
                                .foregroundColor(ColorPalette.textSecondary)

                            Button(
                                action: {
                                    viewModel.showRegistrationScreen()
                                },
                                label: {
                                    Text("Create Account")
                                        .font(Typography.button)
                                        .foregroundColor(ColorPalette.primary)
                                }
                            )
                        }
                        .padding(.top, DesignSystem.Spacing.sm)

                        Spacer()
                    }
                    .padding(.horizontal, DesignSystem.Spacing.xxl)
                }

                // Loading overlay
                if viewModel.isLoading {
                    LoadingOverlay(message: "Signing in...")
                }
            }
            .navigationDestination(isPresented: $viewModel.showRegistration) {
                RegistrationView()
            }
        }
    }
}

#Preview {
    WelcomeView()
}
