disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
  - unused_optional_binding
  - missing_docs
analyzer_rules:
  - unused_declaration

excluded:
  - Pods
  - .build
  - DerivedData
  - IQTracker.xcodeproj
  - IQTrackerTests

line_length:
  warning: 120
  error: 150

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 50
  error: 100

large_tuple:
  warning: 3
  error: 4

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2

reporter: "xcode"
