name: AIQ
options:
  bundleIdPrefix: com.aiq
  deploymentTarget:
    iOS: 16.0
  developmentLanguage: en

settings:
  SWIFT_VERSION: 5.9
  IPHONEOS_DEPLOYMENT_TARGET: 16.0
  TARGETED_DEVICE_FAMILY: 1  # iPhone only
  ENABLE_PREVIEWS: YES

targets:
  AIQ:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - AIQ
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aiq.app
      INFOPLIST_FILE: AIQ/Info.plist
      CODE_SIGN_ENTITLEMENTS: AIQ/AIQ.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      SWIFT_EMIT_LOC_STRINGS: YES
      ENABLE_PREVIEWS: YES
    capabilities:
      Push Notifications: true
    dependencies:
      - sdk: SwiftUI.framework

  AIQTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - AIQTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aiq.tests
      SWIFT_EMIT_LOC_STRINGS: YES
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: AIQ

schemes:
  AIQ:
    build:
      targets:
        AIQ: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - AIQTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
