"""Add question performance statistics fields (P11-007)

Revision ID: 88562b225bce
Revises: 68ba60e646f3
Create Date: 2025-11-16 15:10:00.498228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88562b225bce"
down_revision: Union[str, None] = "68ba60e646f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add Classical Test Theory (CTT) metrics
    # These fields track empirical question performance from user responses
    # Populated by P11-009 after users complete tests
    op.add_column(
        "questions", sa.Column("empirical_difficulty", sa.Float(), nullable=True)
    )  # P-value (proportion correct)
    op.add_column(
        "questions", sa.Column("discrimination", sa.Float(), nullable=True)
    )  # Item-total correlation
    op.add_column(
        "questions", sa.Column("response_count", sa.Integer(), nullable=True)
    )  # Number of responses

    # Add Item Response Theory (IRT) parameters
    # These fields are for future IRT calibration (Phase 12+)
    # Will remain NULL until IRT analysis is implemented
    op.add_column(
        "questions", sa.Column("irt_difficulty", sa.Float(), nullable=True)
    )  # IRT b parameter
    op.add_column(
        "questions", sa.Column("irt_discrimination", sa.Float(), nullable=True)
    )  # IRT a parameter
    op.add_column(
        "questions", sa.Column("irt_guessing", sa.Float(), nullable=True)
    )  # IRT c parameter
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "irt_guessing")
    op.drop_column("questions", "irt_discrimination")
    op.drop_column("questions", "irt_difficulty")
    op.drop_column("questions", "response_count")
    op.drop_column("questions", "discrimination")
    op.drop_column("questions", "empirical_difficulty")
    # ### end Alembic commands ###
