"""Add prompt_version to questions table

Revision ID: d86e6798032c
Revises: 555e7c724405
Create Date: 2025-11-17 10:28:11.070324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d86e6798032c"
down_revision: Union[str, None] = "555e7c724405"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions", sa.Column("prompt_version", sa.String(length=50), nullable=True)
    )

    # Set existing questions to version "1.0" (original prompts)
    op.execute(
        "UPDATE questions SET prompt_version = '1.0' WHERE prompt_version IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "prompt_version")
    # ### end Alembic commands ###
