#!/usr/bin/env python3
"""Test script for the alerting system.

This script sends a test alert to verify that email and file alerts are working correctly.
"""

import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from app.alerting import AlertManager
from app.config import settings
from app.error_classifier import ClassifiedError, ErrorCategory, ErrorSeverity


def main():
    """Send a test alert."""
    print("=" * 80)
    print("Testing Alert System")
    print("=" * 80)

    # Parse email list
    to_emails = []
    if settings.alert_to_emails:
        to_emails = [email.strip() for email in settings.alert_to_emails.split(",")]

    # Initialize alert manager
    print(
        f"\nEmail alerts: {'ENABLED' if settings.enable_email_alerts else 'DISABLED'}"
    )
    if settings.enable_email_alerts:
        print(f"SMTP Host: {settings.smtp_host}:{settings.smtp_port}")
        print(f"From: {settings.alert_from_email}")
        print(f"To: {to_emails}")
    print(f"Alert file: {settings.alert_file_path}")

    alert_manager = AlertManager(
        email_enabled=settings.enable_email_alerts,
        smtp_host=settings.smtp_host,
        smtp_port=settings.smtp_port,
        smtp_username=settings.smtp_username,
        smtp_password=settings.smtp_password,
        from_email=settings.alert_from_email,
        to_emails=to_emails,
        alert_file_path=settings.alert_file_path,
    )

    print("\nCreating test billing error...")

    # Create a test billing error
    test_error = ClassifiedError(
        category=ErrorCategory.BILLING_QUOTA,
        severity=ErrorSeverity.CRITICAL,
        provider="openai",
        original_error="InsufficientQuotaError",
        message=(
            "TEST ALERT: Billing or quota issue detected. "
            "Please check your OpenAI account balance and usage limits. "
            "This is a test alert from the AIQ question service."
        ),
        is_retryable=False,
    )

    print(f"Error category: {test_error.category.value}")
    print(f"Severity: {test_error.severity.value}")
    print(f"Provider: {test_error.provider}")

    print("\nSending test alert...")
    success = alert_manager.send_alert(
        test_error,
        context="This is a test alert generated by test_alerts.py to verify the alerting system is working correctly.",
    )

    print("\n" + "=" * 80)
    if success:
        print("✓ Test alert sent successfully!")
        print("\nWhat to check:")
        if settings.enable_email_alerts:
            print(f"  1. Check your email inbox at: {', '.join(to_emails)}")
            print("  2. Check spam folder if not in inbox")
        print(f"  3. Check alert file at: {settings.alert_file_path}")
        print("\nIf you received the alert, the system is working correctly!")
    else:
        print("✗ Test alert failed to send!")
        print("\nTroubleshooting:")
        print("  1. Check your SMTP credentials in .env")
        print("  2. Verify firewall allows outbound SMTP on port 587")
        print("  3. If using Gmail, ensure you're using an App Password")
        print("  4. Check the logs for error details")

    print("=" * 80)

    # Show alert summary
    summary = alert_manager.get_alerts_summary()
    print(f"\nAlerts Summary:")
    print(f"  Total alerts sent: {summary['total_alerts']}")
    print(f"  Successful: {summary['successful']}")
    print(f"  Failed: {summary['failed']}")

    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
